### ISSUE TITLE
[Request] Feed peers

### ISSUE THREAD

**Issue by ivcosla** [skycoin/skycoin#1671] opened 2018-06-25 07:14 UTC
Currently there are two ways of telling a new node which initial trusted peers connect to:
1) Have a peers.txt file that can be pulled with a GET request. This file has the format address:port. Each line defines a peer.
2) Write a peers.txt that's actually a JSON encoded file into the data directory used by the node. 

If I'm not wrong, right now doesn't matter which way to use, the code will still add the initial hardcoded connections to the new ones, making it impossible to create a new non-localhost network thats isolated from the hardcoded connections.

I think that would be a nice adding to the CLI a way to load a initial set of peers from a given peers.txt that can be stored locally anywhere and which the node won't add the hardcoded ones to.

**Comment by gz-c** [comment] 2018-06-25 22:33
The way it works is:

* There is a hardcoded list of peers
* Optionally, more peers are downloaded from a peers.txt file. This option is disabled by default. The data format is newline separated list of ip:port.
* Peers are acquired through "peer exchange" (pex) 

All peers from above are saved locally in a `peers.txt` file, as JSON, with metadata.

So it depends on what you want.  

If you want to modify the trusted peers we can expose that on the CLI (note that a max of 1 trusted peer is connected to, in the next version).  

If you want to make sure some peers are in the peer list, you can modify the local peers.txt

If you want something else, it will be require multiple changes, such as a new class of peer.

**Comment by ivcosla** [comment] 2018-06-26 02:17
What I want is to run my own network, that doesn't connects to the hardcoded peers, only to the ones I specify on the peers.txt.

I think that the only changes that are required are to enable a new cli flag that allows to pass a peers.txt, then the node will connect to only these peers and exchange as usual.

Another option may be to set a cli flag that makes the hardcoded peers not to be used.

**Comment by olemis** [comment] 2018-06-26 02:31
This is related to the testnet , see [these issues](https://github.com/skycoin/skycoin/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+testnet) .

**Comment by olemis** [comment] 2018-06-26 03:50
This is related to the testnet , see [these issues](https://github.com/skycoin/skycoin/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+testnet) .

**Comment by olemis** [comment] 2018-06-26 03:50
Default peers are specified via command line args in #828 , but that should change .

**Comment by olemis** [comment] 2018-06-26 13:40
I've been reading and this is indeed a duplicate of #828 . Therefore I am closing this issue as duplicate. Feel free to revert this if this is not the case .

**Comment by gz-c** [comment] 2018-06-29 03:10
#828 covers a lot of things, will keep this here since we have a specific use case now

Since these peers are a special case, distinct from hardcoded peers and from peers discovered in peer exchange, the flags suggested by @ivcosla seem appropriate

* Either a flag to disable hardcoded peers, or a flag that sets the hardcoded peers (allowing the user to set them to empty)
* A flag to specify custom peers loaded from a file [separate from the ~/.skycoin/peers.txt file, since the caller will not want it repeatedly modified]

From this I suggest,

- `-disable-trusted-peers` 

This should probably set the trusted peers list to the empty list.  Otherwise, we'd have to always remember to add special handling for this flag in code related to trusted peers.  This may require additional code changes, if existing code assumes that the trusted peer list is not empty.

A second concern is that the "trusted" flag is saved to the `~/.skycoin/peers.txt` file.  If the user already had trusted peers marked in their peers.txt file, then they use this flag, the behavior is hard to define.  Presumably we should unset the trusted flag on all peers loaded from `~/.skycoin/peers.txt` if `-disable-trusted-peers` is set.  And, if `-disable-trusted-peers` is not set, then we should set the trusted flag on peers loaded from peers.txt, if they are in the hardcoded peers list. 

- `-peers-file`

This flag would point to a local file containing newline separated ip:port (the same format as the remote https://downloads.skycoin.net/blockchain/peers.txt file).

If the operator is concerned about their peers breaching the local network they have set up, they will want to reset the `~/.skycoin/peers.txt` file manually between runs, or figure out the source of the bleeding.  In any case, deleting `~/.skycoin/peers.txt` will bring them to a clean state.

**Comment by olemis** [comment] 2018-07-10 05:29
@gz-c this is already implemented in the patch for #828

**Comment by olemis** [comment] 2018-07-10 05:29
.

**Comment by olemis** [comment] 2018-07-10 17:29
Just for the record I mention something in here related to this issue . In my opinion the possibility for configuring peers this way should only be allowed when running a (sim)testnet , which seems to be the case for @ivcosla . That's why the command line argument for this in the patch for #828 is considered only if `--testchain` is set .

I'll propose a patch for this limited use case though .

**Comment by stdevEclipse** [comment] 2018-07-20 17:23
Question:
Should peers be saved in local JSON "peers.txt" file if loaded from URL?
I am asking because this is not done.

**Comment by olemis** [comment] 2018-07-22 02:03
@stdevEclipse Travis failing

**Comment by gz-c** [comment] 2018-08-23 02:15
@ivcosla @olemis feature is added to develop branch, use

`--disable-default-peers` and `--custom-peers-file`

**Closed** 2018-08-23 02:14 UTC
Labels: enhancement, stdev, wip
