### ISSUE TITLE
skycoin-cli transaction, error: index out of range

### ISSUE THREAD

**Issue by adriantpaez** [skycoin/skycoin#2469] opened 2019-07-23 20:27 UTC
When I run the command `skycoin cli-transaction` with out arguments raise next error:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/skycoin/skycoin/src/cli.transactionCmd.func1(0xc420323680, 0xd2b448, 0x0, 0x0, 0x0, 0x0)
	$GOPATH/src/github.com/skycoin/skycoin/src/cli/transaction.go:28 +0x1b2
github.com/skycoin/skycoin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420323680, 0xd2b448, 0x0, 0x0, 0xc420323680, 0xd2b448)
	$GOPATH/src/github.com/skycoin/skycoin/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/skycoin/skycoin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420316000, 0xc420325400, 0xc420325680, 0xc420325900)
	$GOPATH/src/github.com/skycoin/skycoin/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/skycoin/skycoin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420316000, 0x1a, 0xc420312010)
	$GOPATH/src/github.com/skycoin/skycoin/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	$GOPATH/src/github.com/skycoin/skycoin/cmd/cli/cli.go:26 +0x19e

```

**Comment by therealssj** [comment] 2019-08-01 12:27
@stdevAdrianPaez are you on develop? 
I just tried this and I get 
```
❯ skycoin-cli transaction
Error: accepts 1 arg(s), received 0
```

Try to reinstall the cli:
```
cd $GOPATH/src/github.com/skycoin/skycoin/cmd/cli
./install.sh
```

**Comment by BigOokie** [comment] 2019-08-02 00:14
Think this could be a duplicate of #2348

**Comment by therealssj** [comment] 2019-08-04 10:00
@BigOokie looks like its fixed.

**Closed as completed** 2020-12-30 13:01 UTC
Labels: bug, cli
