### ISSUE TITLE
[skycoin.gui:ERROR] Create transaction failed: please spend after your pending transaction is confirmed

### ISSUE THREAD

**Issue by skycoin-manager** [skycoin/skycoin#728] opened 2017-12-09 05:40 UTC
Currently error prints to console
- if user tries to spend out of wallet and there are no unspent outputs to spend
- then show a pop-up error message
- instead of just showing red square at bottom

[skycoin.gui:ERROR] Create transaction failed: please spend after your pending transaction is confirmed

**Comment by gz-c** [comment] 2017-12-09 05:50
Duplicate of #628

**Comment by skycoin-manager** [comment] 2017-12-09 06:11
Not duplicate
- happens when there are connections (#628 is when no networking connections)
- happens when wallet only has one unspent output and an unconfirmed transaction would spend that output (so cannot create new transaction until the previous transaction is spend)

Needs pop notification telling user that they cannot create more transactions until their pending transactions are executed (no-available unspent outputs in the wallet for transaction).

**Comment by gz-c** [comment] 2017-12-09 06:37
#628 is when there is ANY spend error.

The fundamental issue is that the error box is hidden and doesn't display the error message

**Closed** 2018-04-17 03:10 UTC
