### ISSUE TITLE
Add genesis hash in INTR message package

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#2335] opened 2019-05-17 02:43 UTC
The genesis pubkey was added mistakenly in INTR message package, it should be the genesis hash. Add the genesis hash and keep both of them in the INTR message in v26. Require and verify it in next version.

**Comment by gz-c** [comment] 2019-05-17 02:57
Duplicate of #2325 #2334

**Closed by gz-c** 2019-05-17 02:57 UTC
