### ISSUE TITLE
Blank screen issue on electron OS X builds v23

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1497] opened 2018-05-14 15:07 UTC
Multiple users have reported a white screen on startup, OS X v0.23.0

From one of the users' logs, it appears that `visor.Visor` closes prematurely, with no other information.  From the code, it seems that this would be a problem with the initial `maybeCreateGenesisBlock` step.

The solution is to delete data.db.  We are waiting to obtain a copy of a bad data.db to investigate, and see if it is still an issue since the database refactor.

**Comment by iketheadore** [comment] 2018-05-16 15:55
The main problem is caused by the in-memory cache we created for the boltdb bucket.

In `daemon.Run()` method, we start the `visor`, `pool`, etc., in separate goroutines, and have a `for select loop` in the end. In `visor.Run` method, we would try to remove all invalid unconfirmed transactions, the `blockchain.Head()` method would be called in the method. There're two steps to get the blockchain head, we get the head seq first, then get block of that seq from db. 

By the time we're verifying the unconfirmed transactions, we might receiving messages from other nodes, like `GiveBlocksMessage`, the daemon would get the message from the `for  select loop` in the `case m := <-dm.messageEvents:`. Checking the `GiveBlocksMessage.Process()` method, it would execute all the received blocks and update the blockchain. The problem here is the head seq cache is updated before the boltdb is committed, and in the visor, if we try to get head block, we would get `found no head block:` error, as head seq in cached is updated, but block data has not been committed.

The `visor.Run()` would return that error and push the error to `errC` to try to break the `daemon for select loop`, but the `GiveBlocksMessage.Process` is stuck, as it calls `visor.ExecuteSignedBlock` to process block, which calls `strand.Strand` and have `visor.reqC` as request channel. When `visor.Run` is returned, the reader of the `visor.reqC` is disappeare, and the `visor.ExecuteSignedBlock` would never be returned.  So the daemon's `for select loop` would be stuck as well, and the `case <- errC` could never be triggered, then the whole daemon would stop working.

Though the latest develop branch has removed the db cache and once the [1503](https://github.com/skycoin/skycoin/pull/1503) is merged, we should not have this problem, but when I run #1503 branch code with the broken db, I got another error: `Failed to execute received block 22701: HistoryDB.ParseBlock: transaction input not found in outputs bucket`, which I think the broken db has some outputs lost. so maybe we need to check if all outputs against the blockchain are exist when we checking if db is corrupted.

**Comment by gz-c** [comment] 2018-05-16 17:03
@iketheadore ok, add historydb verifier

I think if we save the version to the db (#1467) then we can handle this more easily.

Assuming that we know that we fixed the cause of corruption, we do not need to check every time, only when they start the new version for the first time.  Then, we could just rebuild the entire historydb and other indexes from the blockchain on startup once.

For now, we'll add the verifier and use it to monitor, but also should save the version, so that in later versions we can simplify database upgrading.

**Comment by gz-c** [comment] 2018-05-26 14:05
This can also happen if peers.txt load or save during init fails.

I think any init error will have blank screen problem. So electron will need to handle this somehow.

**Closed** 2018-06-07 12:34 UTC
Labels: bug
