### ISSUE TITLE
[V20.3  GUI Send Decimal]UI got stuck when trying to send decimal value

### ISSUE THREAD

**Issue by candyYMMA** [skycoin/skycoin#626] opened 2017-11-21 23:51 UTC
Platform:
Linux Ubuntu 16.4(64 bit)

Scenario:
Click on Load wallet from Seed.
Seed is loaded.
Go to send tab.
Insert details - Address, choose your wallet, enter decimal number for example 0.1.
Press Send.

Expected:
Error message should appear on the screen - "Operation is not supported" or something like it.

Actual:
Red label appears with not text on it.
All wallet is stuck and my entire browser(chrome) got stuck and not responding.
![screenshot from 2017-11-22 01-13-58](https://user-images.githubusercontent.com/28111034/33102872-7e00750e-cf27-11e7-989a-fd829ab359b2.png)

**Comment by gz-c** [comment] 2017-11-22 05:00
Related: #628

**Comment by gz-c** [comment] 2017-11-22 15:32
Marking as duplicate of #628

**Closed by gz-c** 2017-11-22 15:32 UTC
Labels: wallet
