### ISSUE TITLE
Send peerlist message before disconnecting due to a full peer list

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#670] opened 2017-11-27 15:00 UTC
When a client connects to a node whose peerlist is full, that node will then disconnect the client.

The node should share its peer with the client before disconnecting, so that the node can find peers that they can reliably connect to.

**Comment by olemis** [comment] 2018-03-17 04:44
@gz-c this is a duplicate of #735 . Should we close it ?

**Closed** 2018-03-17 05:20 UTC
Labels: core, stdev, wip
