### ISSUE TITLE
Version the REST API

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#485] opened 2017-08-21 10:32 UTC
API endpoints need to be prefixed with something like `/v1/` so we can handle breaking changes.
Need to figure out plan for how to do this correctly

**Comment by olemis** [comment] 2018-05-01 19:04
Will this support different versions running in parallel (e.g. support `vx.y` for a while before deprecating it in favor of `v(x+1).y` so that implementors have time to migrate)

**Comment by gz-c** [comment] 2018-05-02 05:28
yes

**Comment by olemis** [comment] 2018-05-18 02:17
@gz-c is this a duplicate of #1444 ?

**Closed** 2018-05-18 05:34 UTC
Labels: api, core, stdev, wip
