### ISSUE TITLE
API endpoints to create unsigned transaction and sign unsigned transaction from unspent outputs

### ISSUE THREAD

**Issue by stdevEclipse** [skycoin/skycoin#1776] opened 2018-08-14 15:36 UTC
It would be great to have the option in Skycoin to be able to create the transaction unsigned. No need to provide wallet, and no need for signing.
The transaction would be signed afterwards.

**Comment by Senyoret1** [comment] 2018-08-15 11:34
This is related to https://github.com/skycoin/skycoin/issues/1513 .

The possibility of creating transactions without specifying a wallet (probably just with the inputs and outputs) is important to improve the web wallet. I thought that was part of https://github.com/skycoin/skycoin/issues/1513 or another issue, but I could not find it, so 👍 to this issue.

**Comment by gz-c** [comment] 2018-08-21 05:33
#1513 can be done first, then modified to accept unspent outputs directly

**Comment by gz-c** [comment] 2018-08-21 05:35
Closing this as duplicate of #1461

**Closed by gz-c** 2018-08-21 05:35 UTC
