### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1087] opened 2018-03-17 04:54 UTC
We have some flaky test(s)
PR https://github.com/skycoin/skycoin/pull/1085 failed once but passed when I restarted the test. 
It failed only on go1.10

**Comment by gz-c** [comment] 2018-03-17 05:06
Possible duplicate of #978 #933 

Need logs to diagnose

**Closed by gz-c** 2018-03-17 05:06 UTC
